### ISSUE TITLE
这篇论文中没有提到召回部分，LECARDV2数据集应该需要召回吧

### ISSUE THREAD

**Issue by hecongqing** [ChenlongDeng/KELLER#1]

**Comment by ChenlongDeng** [comment]
LeCaRDv2数据集上采用官方的完全标注集作为召回的结果，这样能够更好避免噪声对结果的影响

**Comment by hecongqing** [comment]
好的 我理解也就是每一个query都和candidate的所有doc进行ranking

**Comment by ChenlongDeng** [comment]
> 好的 我理解也就是每一个query都和candidate的所有doc进行ranking

是的，我们的实验将每个query下有标注的docs作为candidates，在这个集合中做reranking

**Comment by hecongqing** [comment]
好的 谢谢
