### ISSUE TITLE
BERT、RoBERTa等baseline的实现细节

### ISSUE THREAD

**Issue by hecongqing** [ChenlongDeng/KELLER#4]
在LeCaRDv2数据集上，是否先用BM25召回，然后基于BERT的cross-encoder做reranking的模型

**Comment by ChenlongDeng** [comment]
在LeCaRDv2数据集上，与论文中的描述相同：由于标注集合中的文档几乎全部为相关文档，导致评价指标偏高且缺乏区分度。因此，我们从BM25检索得到的top100-150结果中随机采样了10个负样例文档，将其补充到候选文档集合中做重排，而非直接使用BM25的检索结果进行重排序。
